### ISSUE TITLE
Test failure in version 0.2.0.0

### ISSUE THREAD

**Issue by qrilka** [Bodigrim/exp-pairs#16]
Using version 0.2.0.0 of the package and LTS-13 gives me the following failure with `stack test`:
```
    reverseMOnS . mOnS == id:             1.1795345243327954e-3
1.1380441420676078e-3
1.1354513099134343e-3
1.1341549037472965e-3
1.1340738786831009e-3
1.1340726127735355e-3
1.134072593196353e-3
1.1340725834077618e-3
1.134072580960614e-3
1.134072580715899e-3
1.1340725806989027e-3
1.1340725806799651e-3
1.1340725806615395e-3
FAIL (31.85s)
      *** Failed! Falsifiable (after 72 tests and 12 shrinks):
      648426237161 % 954006417892
      Use --quickcheck-replay=743495 to reproduce.
    mOnS . reverseMOnS == id:             OK (0.08s)
      14 tests completed
```
Because of it this package will be added to `expected-test-failures` on Stackage

**Comment by Bodigrim** [comment]
Thanks for reporting. It is basically a too strict test, nothing wrong in the package itself. I relaxed the test, but I do not want to make a new release just for this reason, so let us leave `exp-pairs` in `expected-test-failures` for a while.
